patch:
  patch_length: 16
  stride: 16
  n_channels: 5

revin:
  eps: 1.0e-5
  affine: false

encoder:
  in_channels: 5
  hidden_channels: 128
  latent_dim: 64
  n_layers: 4
  dilation_base: 2
  kernel_size: 3

decoder:
  latent_dim: 64
  hidden_channels: 128
  out_channels: 5
  patch_length: 16
  n_layers: 4
  kernel_size: 3

codebook:
  num_codes: 1024
  latent_dim: 64
  ema_decay: 0.99
  eps: 1.0e-5
  dead_threshold: 2
  commitment_weight: 0.25

loss:
  huber_delta: 1.0
  sdtw_alpha: 0.1
  sdtw_gamma: 0.1
  commitment_beta: 0.25

training:
  lr: 3.0e-4
  weight_decay: 1.0e-2
  max_epochs: 200
  warmup_epochs: 5
  patience: 20
  batch_size: 64
  num_patches: 32
  precision: '16-mixed'

data:
  data_path: 'data/'
  val_split: 0.2
  num_workers: 4
